ENV["EMAIL_USER_NAME"] = 'answerawesome'
ENV["EMAIL_PASSWORD"] = 'Sup3r$ecret$$'
ENV['AWS_ACCESS_KEY_ID'] = 'AKIAIP2IZCKVU5VYUGSA'
ENV['AWS_SECRET_ACCESS_KEY'] = '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'
